version: "3"
services:
  sftp:
    image: atmoz/sftp:alpine-3.7
    volumes:
      - ./upload:/home/sftp-user/upload
      - ../src/main/resources/keystore/my-sshkey.pub:/home/sftp-user/.ssh/keys/my-sshkey.pub:ro
    ports:
      - "2222:22"
    command: sftp-user:passwd:::upload